github: [windmillcode]
patreon: windmillcode
ko_fi: windmillcode
open_collective: windmill-code
community_bridge: 42056b04-305f-4e08-929c-66725181d6af
liberapay: windmillcode
tidelift: npm/windmillcode
polar: windmillcode
thanks_dev: windmillcode
custom:
  - "https://www.gofundme.com/f/strengthen-our-business-to-take-on-bigger-initiati?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer"


